"""shipping table created

Revision ID: 0fc87e00960a
Revises: 1bee9803e84c
Create Date: 2021-10-11 18:02:33.876885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc87e00960a'
down_revision = '1bee9803e84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_companies',
    sa.Column('shipping_company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('cnpj', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('shipping_company_id'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping_companies')
    # ### end Alembic commands ###
