"""products table created

Revision ID: 41d41bc349f2
Revises: fc5365c155e5
Create Date: 2021-10-11 09:58:03.893647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d41bc349f2'
down_revision = 'fc5365c155e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.String(length=511), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('weight', sa.String(length=16), nullable=True),
    sa.Column('height', sa.String(length=16), nullable=True),
    sa.Column('length', sa.String(length=16), nullable=True),
    sa.Column('width', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
