"""creating order adresses table

Revision ID: 4916c6cfde7f
Revises: 41d41bc349f2
Create Date: 2021-10-11 15:04:05.337547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4916c6cfde7f'
down_revision = '41d41bc349f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_adresses',
    sa.Column('order_adress_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('house_number', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('cep', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('order_adress_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_adresses')
    # ### end Alembic commands ###
