"""Changing columns to not null order product

Revision ID: 580e6796fe6d
Revises: c6386f7a616f
Create Date: 2021-10-12 00:07:10.060918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580e6796fe6d'
down_revision = 'c6386f7a616f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_product', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders_product', 'total_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_product', 'total_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders_product', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
