"""product_image table created

Revision ID: 998973b9329b
Revises: 580e6796fe6d
Create Date: 2021-10-14 18:47:03.409303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998973b9329b'
down_revision = '580e6796fe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('product_image_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_image_id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    # ### end Alembic commands ###
