"""adding minimum shipping price to shipping companies table

Revision ID: 9a6c8eb30815
Revises: 7309a0f4a19d
Create Date: 2021-10-17 13:19:34.594403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6c8eb30815'
down_revision = '7309a0f4a19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_companies', sa.Column('minimum_shipping_price', sa.Integer(), nullable=True))
    op.execute("UPDATE shipping_companies SET minimum_shipping_price = 0 WHERE minimum_shipping_price is NULL")
    op.alter_column('shipping_companies', 'minimum_shipping_price', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_companies', 'minimum_shipping_price')
    # ### end Alembic commands ###
