"""creating orders and orders product table

Revision ID: c6386f7a616f
Revises: bdf29d02ce62
Create Date: 2021-10-11 21:56:59.054261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6386f7a616f'
down_revision = 'bdf29d02ce62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('adress_id', sa.Integer(), nullable=True),
    sa.Column('shipping_company_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adress_id'], ['orders_adresses.order_adress_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.ForeignKeyConstraint(['shipping_company_id'], ['shipping_companies.shipping_company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('orders_product',
    sa.Column('orders_product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('orders_product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_product')
    op.drop_table('orders')
    # ### end Alembic commands ###
