"""img column created in products table

Revision ID: f5063f2ab7c9
Revises: 580e6796fe6d
Create Date: 2021-10-14 16:30:31.075441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5063f2ab7c9'
down_revision = '580e6796fe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img')
    # ### end Alembic commands ###
