
class InvalidTypeError(Exception):
    ...

class InvalidCpfFormatError(Exception):
    ...

class InvalidCellphoneFormatError(Exception):
    ...

class InvalidKeysError(Exception):
    ...

class WrongPasswordError(Exception):
    ...